import Link from "next/link";
import { getJSON, type CompanySummary } from "@/lib/api";

const MODULES = [
  {
    title: "Data Sheets",
    text: "Download auditable Excel models for any covered company. As-reported numbers in blue, each one hyperlinked to the exact SEC filing it came from; margins and free cash flow as live formulas.",
    href: "/dashboard",
    cta: "Browse coverage",
  },
  {
    title: "Excel Add-in",
    text: "Pull any value into any cell with =BOE.VALUE(), insert full models at your cursor, and refresh every formula in the workbook with one click.",
    href: "/addin",
    cta: "See setup guide",
  },
  {
    title: "Scout",
    text: "Screen companies in plain English. Your question becomes a structured filter — every number computed from the database, never generated by the model.",
    href: "/scout",
    cta: "Run a screen",
  },
  {
    title: "Templates",
    text: "Define your own model layout — custom row order and calculated lines like Adjusted EBITDA — save it once, and every data sheet you download applies it automatically.",
    href: "/templates",
    cta: "Build a template",
  },
  {
    title: "Developer API",
    text: "The same validated fundamentals as clean JSON: REST endpoints with an SEC audit URL on every value, keyed access, and tier-based rate limits.",
    href: "/developers",
    cta: "Read the API docs",
  },
  {
    title: "Point-in-Time Values",
    text: "Every period keeps both the originally-reported and the restated figure. Query latest, original, or every vintage — so backtests see what the market saw at the time.",
    href: "/developers",
    cta: "See how it works",
  },
];

const AUDIENCES: { title: string; text: string; href?: string; cta?: string }[] = [
  {
    title: "For analysts",
    text: "Stop re-keying filings. Open a company, download the model, and verify any number against its source in one click.",
  },
  {
    title: "For developers",
    text: "A REST API with audit URLs on every value. Feed clean, validated fundamentals into your own systems and backtests.",
    href: "/developers",
    cta: "Read the API docs",
  },
  {
    title: "For teams",
    text: "Shared model templates keep everyone's spreadsheets consistent — one layout, applied to every company, every time.",
  },
];

const STEPS = [
  {
    n: "1",
    title: "Ingest",
    text: "A filing monitor polls EDGAR and re-ingests companies as new filings appear. Structured XBRL for the statements; an LLM reads MD&A and footnotes for the KPIs tables don't carry.",
  },
  {
    n: "2",
    title: "Validate",
    text: "Every SEC-extracted annual figure is cross-checked against an independent source. Disagreements over 1% are flagged for human review — never silently published.",
  },
  {
    n: "3",
    title: "Deliver",
    text: "Web, Excel, or JSON — the same validated data everywhere, and every number one click from the SEC page it was reported on.",
  },
];

export default async function Landing() {
  const companies = await getJSON<CompanySummary[]>("/companies");
  const coverage = companies?.length ?? 0;

  return (
    <>
      {/* Announcement bar */}
      <div className="announce">
        Data Sheets, Excel Add-in, Scout, Templates, and the Developer API.{" "}
        <Link href="/dashboard">Take a look</Link>
      </div>

      {/* Hero + stat block */}
      <section className="hero">
        <h1 className="hero-title">
          Fundamentals you can trace.
          <br />
          Models you can trust.
        </h1>
        <p className="hero-sub">
          BOE Analytics turns raw SEC filings into analyst-ready data: every
          line item extracted, validated, and linked back to the exact page it
          was reported on. No black boxes between you and the source.
        </p>
        <p>
          <Link href="/dashboard" className="btn hero-btn">Open the dashboard</Link>{" "}
          <Link href="/developers" className="btn secondary hero-btn">Developer API</Link>
        </p>
        <div className="stats-row">
          <div className="stat">
            <div className="stat-num">{coverage || "—"}</div>
            <div className="stat-label">companies covered, growing per ingest</div>
          </div>
          <div className="stat">
            <div className="stat-num">2 sources</div>
            <div className="stat-label">SEC-extracted values cross-checked against an independent provider</div>
          </div>
          <div className="stat">
            <div className="stat-num">100%</div>
            <div className="stat-label">of SEC-extracted numbers linked to the exact filing; baseline data marked as such</div>
          </div>
        </div>
      </section>

      {/* Coverage ticker strip: SEC-extracted names first, then baseline */}
      {companies && companies.length > 0 && (
        <div className="ticker-strip">
          {[...companies]
            .sort((a, b) =>
              a.source === b.source ? 0 : a.source === "sec" ? -1 : 1,
            )
            .slice(0, 40)
            .map((c) => (
              <Link key={c.ticker} href={`/company/${c.ticker}`}>{c.ticker}</Link>
            ))}
          {companies.length > 40 && (
            <span className="muted">
              …and {(companies.length - 40).toLocaleString()} more
            </span>
          )}
        </div>
      )}

      {/* Value proposition */}
      <section className="two-col">
        <div>
          <h2>Hours of re-keying, gone.</h2>
          <p className="muted" style={{ fontSize: 16, lineHeight: 1.6 }}>
            Building a model from a 10-K means hand-copying hundreds of numbers
            — and hoping none of them slipped. BOE Analytics extracts the full
            statement history for you, labels every period against the
            company&apos;s own fiscal calendar, and derives the fourth quarter
            when companies don&apos;t report it discretely.
          </p>
        </div>
        <div className="card">
          <h3 style={{ marginTop: 0, color: "var(--navy)" }}>The old way vs. BOE Analytics</h3>
          <table>
            <tbody>
              <tr><td>Collect 10 years of statements</td><td className="num">hours → <b>seconds</b></td></tr>
              <tr><td>Verify a suspicious number</td><td className="num">dig through filings → <b>one click</b></td></tr>
              <tr><td>Apply your model layout</td><td className="num">rebuild each time → <b>saved template</b></td></tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* Accuracy / transparency statement */}
      <section className="cta-panel" style={{ textAlign: "left", padding: "40px 48px" }}>
        <h2 style={{ margin: 0 }}>Auditable by design, validated by default.</h2>
        <p style={{ maxWidth: 720 }}>
          Every SEC-extracted value carries the accession number, form type,
          and filing date it came from — and a link to the document itself —
          and is cross-checked against an independent data source before it
          reaches your model; disagreements beyond 1% go to a human review
          queue instead of into your spreadsheet. Baseline coverage
          (standardized data pending SEC extraction) is always marked as such.
        </p>
      </section>

      {/* Audience cards */}
      <section>
        <h2>Built for how you work</h2>
        <div className="usecase-grid">
          {AUDIENCES.map((a) => (
            <div key={a.title} className="card feature-card">
              <h3>{a.title}</h3>
              <p className="muted">{a.text}</p>
              {a.href && a.cta && <Link href={a.href}>{a.cta} →</Link>}
            </div>
          ))}
        </div>
      </section>

      {/* Product suite grid */}
      <section>
        <h2>The product suite</h2>
        <div className="feature-grid">
          {MODULES.map((m) => (
            <div key={m.title} className="card feature-card">
              <h3>{m.title}</h3>
              <p className="muted">{m.text}</p>
              <Link href={m.href}>{m.cta} →</Link>
            </div>
          ))}
        </div>
      </section>

      {/* Data breadth statement */}
      <section className="two-col">
        <div>
          <h2>Deep history, both vintages.</h2>
          <p className="muted" style={{ fontSize: 16, lineHeight: 1.6 }}>
            Coverage reaches back a decade or more per company — annual and
            quarterly, income statement through balance sheet — and the
            database keeps <i>both</i> the originally-reported and the restated
            value for every period. Niche, sector-specific KPIs are extracted
            from filing prose with the verbatim sentence attached, so nothing
            enters the dataset without a paper trail.
          </p>
        </div>
        <div>
          <h2>How it works</h2>
          {STEPS.map((s) => (
            <p key={s.n} style={{ lineHeight: 1.55 }}>
              <b style={{ color: "var(--navy)" }}>{s.n}. {s.title}</b>{" "}
              <span className="muted">{s.text}</span>
            </p>
          ))}
        </div>
      </section>

      {/* Closing CTA */}
      <section className="cta-panel">
        <h2>Every number, one click from its filing.</h2>
        <p>
          Open a company, click any figure, and land on the SEC document it was
          reported in. That&apos;s the whole product philosophy.
        </p>
        <Link href="/dashboard" className="btn hero-btn">Get started</Link>{" "}
        <Link href="/scout" className="btn secondary hero-btn">Try Scout</Link>
      </section>
    </>
  );
}
